# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Homework 41' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Homework 41
   pod 'Localize' , '~> 2.3.0' end
